###REGISTER NEW USER
POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "Usuario2 desde register",
    "email": "usuario3@email.com",
    "password": "contraseña"
}

###LOGIN (USER)
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Usuario2 desde register",
    "password": "contraseña"
}

###LOGIN (USER2)
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Usuario desde register",
    "password": "contraseña"
}

###LOGIN (ADMIN)
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "admin",
    "password": "123456"
}



###LOGOUT
POST http://localhost:4000/logout

###REFRESH
POST http://localhost:4000/refresh

###VERIFY IF USER IS LOGGED
GET http://localhost:4000/auth/me