###GET ALL BOARDS (RESULT DEPENDS ON ROLE)
GET http://localhost:4000/boards

###GET ALL BOARDS (RESULT DEPENDS ON ROLE)
###BY STATUS
GET http://localhost:4000/boards?status=hold

###CREATE NEW BOARD BY CURRENT USER
POST http://localhost:4000/boards
Content-Type: application/json

{
    "name": "Board 3",
    "description": "Board 3 User 2"
}

###GET BOARD BY ID (DEPENDS ON ROLE)
GET http://localhost:4000/boards/68d440f0da39abbc3593a948

###GET BOARD BY ID (DEPENDS ON ROLE)
GET http://localhost:4000/boards/68d4327456c142a741735bf7

###UPDATE BOARD (USER IS ADMIN OR BOARD OWNER)
PUT http://localhost:4000/boards/68d440f0da39abbc3593a948
Content-Type: application/json

{
    "description": "Board 3 User 2 modified2"
}

###UPDATE BOARD (USER IS NOT ADMIN OR BOARD OWNER)
PUT http://localhost:4000/boards/68d4327456c142a741735bf7
Content-Type: application/json

{
    "description": "Board 3 User 2 modified"
}
