###GET ALL BOARDS FOR A USER
GET http://localhost:4000/boards

###CREATE NEW BOARD BY CURRENT USER
POST http://localhost:4000/boards
Content-Type: application/json

{
    "name": "Board 1",
    "description": "Board 1",
    "status": "hold"
}