###GET ALL BOARDS (RESULT DEPENDS ON ROLE)
GET http://localhost:4000/boards

###CREATE NEW BOARD BY CURRENT USER
POST http://localhost:4000/boards
Content-Type: application/json

{
    "name": "Board 2",
    "description": "Board 2 User 2",
    "status": "hold"
}